nginx:
  image: "nginx:latest"
  ports:
    - 443:443
  links:
    - registry:registry
  restart: always
  volumes:
    - /data/registry/auth/:/etc/nginx/conf.d

registry:
  image: registry:2.2.1
  ports:
    - 127.0.0.1:5000:5000
  restart: always
  volumes:
    - /data/registry/data:/var/lib/registry
